### PR TITLE
Fix: navigation using `GlobalKey` instead of `BuildContext`

### PR DESCRIPTION
**Pull request by ansh-les**
## Description

**Features**

**Bugs**

**What kind of change does this PR introduce?** (check at least one)

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Hotfix (fixes a breaking changes)
- [ ] New Feature (non-breaking change which adds functionality)
- [ ] Other, please describe:

### Author Checklist

- [ ] Assignee added
- [ ] Reviewer added
- [ ] Description added
- [ ] Unit test cases added

### Reviewer Checklist

- [ ] PR title starts with Jira ticket number prefix
- [ ] If hotfix, Add Hotfix as prefix in PR title
- [ ] Label added
- [ ] Commit messages follows standard format (added, changed, removed, code commented and chore)
- [ ] Description about the Feature/ Bugs added

### CODE REVIEW

**Comment by ansh-les** [comment]
@divyanshgandhilm Please review this

**Review by divyanshgandhilm — APPROVED** [review]

**Comment by divyanshgandhilm** [comment]
Approved the request, but can you remove all files except the `share_post.dart` file

**Comment by ansh-les** [comment]
#58

**Comment by ansh-les** [comment]
Closing this one then.
Please refer to #58

**Pull request closed without merging**
